spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Alexauu/SpringCloudDemo
          searchPaths: config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/