spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Alexauu/SpringCloudConfig
          searchPaths: respo

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/